### ISSUE TITLE
Does not work...

### ISSUE THREAD

**Issue by homburg** [medovob/workflowy-for-coders#2]
Can't seem to get any code higlighting.

I am using Workflowy+ (paid)

**Comment by medovob** [comment]
Thanks Thomas. Not sure what's changed in Workflowy but adding a small delay seems to fix this now. Let me know if you have any further problems. Should update in the webstore shortly

**Comment by ryandeussing** [comment]
I seem to be having the same issue - no ~~Markdown or~~ code highlighting in notes. Any ideas? I'm really looking forward to this ;)

Update: Markdown working, highlighting still not.

**Comment by medovob** [comment]
Hi Ryan. It seems to work ok for me. You create code blocks using a 4 space indent, the syntax highlighter should kick in automatically. If this isn't working, please send the markdown you are using and I'll have a look

**Comment by ryandeussing** [comment]
How odd - both my issues seem to have been solved after waiting a couple hours. Thanks!
