### ISSUE TITLE
Hides note text completely

### ISSUE THREAD

**Issue by bheylin** [medovob/workflowy-for-coders#3]
Hi for a while activating this plugin causes the entire note area to disappear. Disabling the plugin and refreshing the page shows the note area again.

The text content is still in the html but the CSS has display: none.

I'm using chrome build: 20.0.1132.47 m
on both OSX Lion (10.7.4) and Windows 7 (SP1)

Thanks for your time

Brian

**Comment by medovob** [comment]
Thanks for reporting this Brian - should be working now

**Comment by bheylin** [comment]
Thanks @medovob 
Do you update the chrome web store regularly, or should I install an update directly from github?

**Comment by medovob** [comment]
Yes - I have published to the web store. I'm not sure how often Chrome polls the store for updates but it sometimes takes a few hours. You can force the update by removing the extension and reinstalling from the web store. You should be on version 1.2.4.

**Comment by bheylin** [comment]
It's updated now, thanks
