### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by tjmcewan** [medovob/workflowy-for-coders#8]
I installed the extension, visited my workflowy page, and added some markdown syntax.  I've reloaded the page several times now, but I see no rendering.  I've jumped up and down nodes to no avail.

I'm on Chrome 25.

**Comment by medovob** [comment]
It seems to be working just fine for me in Chrome 25 and I've not had any other reports.

Could you please post the markdown that you are trying to render and see if there are any errors logged in your console

**Comment by tjmcewan** [comment]
You know, now that I realise it's only in the notes, I see about 5 instances of the word on the readme page.  Before that, I could've sworn it said nothing about notes.  Sorry about that. :(
